version: "3.4"
services:
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: .deploy/Dockerfile
      args:
        IMAGE_NAME: webfux/php82-fpm
        IMAGE_TAG: 1.0.0
        APP_ENV: prod
      target: production
    working_dir: /var/app/public
    environment:
      PHP_FPM_LISTEN: /socket/fpm.sock
    volumes:
      - sockets:/socket
      # just temporarily: has to be moved into nginx base image
      - ./php/.deploy/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro
      - ./php/.deploy/php-fpm.d/zzz_200_www_listen.conf:/usr/local/etc/php-fpm.d/zzz_200_www_listen.conf:ro
      - ./php/.deploy/docker-entrypoint.d/99-unix-socket-user.sh:/docker-entrypoint.d/99-unix-socket-user.sh:ro

  webserver:
    container_name: webserver
    build:
      context: ./webserver
      dockerfile: .deploy/Dockerfile
      args:
        IMAGE_NAME: webfux/nginx
        IMAGE_TAG: 1.0.0
        APP_ENV: prod
      target: production
    working_dir: /var/html/www
    ports:
      - target: 80
        published: 80
    environment:
      - BASE_DOMAIN=webfux.io
      - WWW_SUB_DOMAIN=www.dev
      - API_SUB_DOMAIN=api.dev
      - API_SOCKET=/socket/fpm.sock
    volumes:
      - sockets:/socket
      # just temporarily: has to be moved into nginx base image
      # missing function => get username from nginx.conf
      - ./webserver/.deploy/docker-entrypoint.d/99-unix-socket-user.sh:/docker-entrypoint.d/99-unix-socket-user.sh:ro
        
volumes:
  sockets:
