version: "3.9"
services:
  app:
    container_name: app
    build:
      context: ./php
      dockerfile: .deploy/Dockerfile
      target: dev
    volumes:
      - ./php/.deploy/docker-entrypoint.d:/usr/local/bin/docker-entrypoint.d
      # mount PHP application (only local, production COPY)
      - ./php:/var/app
  webserver:
    build:
      context: ./webserver
      dockerfile: .deploy/Dockerfile
      target: dev
    volumes:
      - ./webserver/public:/var/html/www
      - ./webserver/.deploy/templates:/etc/nginx/templates/:ro
