version: "3.9"
services:
  webserver:
    build:
      context: ./webserver
      dockerfile: .deploy/Dockerfile
      target: dev
    volumes:
      - ./webserver/public:/var/html/www
      - ./webserver/.deploy/templates:/etc/nginx/templates/:ro