version: "3.4"
services:
  webserver:
    container_name: webserver
    build:
      context: ./webserver
      dockerfile: .deploy/Dockerfile
      args:
        IMAGE_NAME: webfux/nginx
        IMAGE_TAG: 1.1.0
      target: production
    ports:
      - target: 80
        published: 80
    environment:
      - BASE_DOMAIN=webfux.io
      - WWW_SUB_DOMAIN=www.dev
