version: "3.9"
services:
  webserver:
    container_name: webserver
    build:
      context: ./webserver
      dockerfile: .deploy/Dockerfile
      args:
        IMAGE_NAME: webfux/nginx
        IMAGE_TAG: 1.0.1
      target: production
    ports:
      - target: 80
        published: 80
    environment:
      - DOMAIN=webfux.io
      - WEBSERVER_SUB_DOMAIN=www.dev
